# Generated by Django 5.2 on 2026-09-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('FREE', 'Free map'), ('GOOGLE', 'Google Maps')], default='FREE', help_text='Which map the dashboard and the customer app draw.', max_length=10)),
                ('google_api_key', models.CharField(blank=True, help_text='Google Maps Platform API key. Needs Maps JavaScript API, Map Tiles API and Geocoding API enabled on it.', max_length=200)),
                ('tile_session', models.CharField(blank=True, editable=False, max_length=100)),
                ('tile_session_expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Map Settings',
                'verbose_name_plural': 'Map Settings',
            },
        ),
    ]
