# Generated by Django 5.2 on 2026-07-20 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_service_services_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotlightBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('background_image', models.ImageField(upload_to='spotlight_banners/')),
                ('button_text', models.CharField(default='Book now', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spotlight_banners', to='services.servicecategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spotlight_banners', to='services.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Spotlight Banners',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
