# Generated by Django 5.2 on 2026-08-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('services', '0006_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='header_banners/')),
                ('title', models.CharField(blank=True, help_text='Big text drawn over the image. Leave blank to show the image only.', max_length=120)),
                ('subtitle', models.CharField(blank=True, help_text='Small text under the title', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_banners', to='services.servicecategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_banners', to='services.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Header Banners',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
