# Generated by Django 5.2 on 2026-08-11 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sections', '0002_homesection_home_display_limit_homesection_subtitle'),
        ('promotions', '0002_headerbanner'),
        ('services', '0006_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promo_cards/')),
                ('badge_text', models.CharField(blank=True, help_text='Small chip at the top, e.g. New Launch', max_length=40)),
                ('badge_color', models.CharField(default='#9C1458', help_text='Hex colour of the badge chip', max_length=7)),
                ('title', models.CharField(help_text='e.g. Korean Facials at home', max_length=120)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. From ₹1,899', max_length=120)),
                ('button_text', models.CharField(default='Book now', max_length=40)),
                ('placement', models.CharField(choices=[('BEFORE_SECTIONS', 'Before all home sections'), ('AFTER_SECTION', 'After a specific home section'), ('AFTER_SECTIONS', 'After all home sections')], default='AFTER_SECTIONS', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first within the same placement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('after_section', models.ForeignKey(blank=True, help_text="Only used when placement is 'After a specific home section'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_cards', to='home_sections.homesection')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_cards', to='services.servicecategory')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_cards', to='services.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Promo Cards',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
