# Generated by Django 5.2 on 2026-08-26 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_promocard'),
        ('vendors', '0007_vendor_experience_years_vendor_is_pro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerbanner',
            name='pro_vendor',
            field=models.ForeignKey(blank=True, help_text="Open this Pro Vendor's profile when the customer taps", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_banners', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='promocard',
            name='pro_vendor',
            field=models.ForeignKey(blank=True, help_text="Open this Pro Vendor's profile when the customer taps", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_cards', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='spotlightbanner',
            name='pro_vendor',
            field=models.ForeignKey(blank=True, help_text="Open this Pro Vendor's profile when the customer taps", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spotlight_banners', to='vendors.vendor'),
        ),
    ]
