# Generated by Django 5.2 on 2026-08-28 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0012_booking_preferred_vendor'),
        ('customers', '0003_serviceview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('razorpay_signature', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Rupees, snapshotted from the booking when the order was created', max_digits=10)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('CREATED', 'Order created'), ('ATTEMPTED', 'Checkout opened'), ('CAPTURED', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially refunded')], db_index=True, default='CREATED', max_length=20)),
                ('payout_status', models.CharField(choices=[('HELD', 'Held by platform'), ('RELEASED', 'Released to vendor'), ('REFUNDED', 'Returned to customer')], db_index=True, default='HELD', help_text='Whether the captured money has left the platform yet', max_length=10)),
                ('method', models.CharField(blank=True, help_text='upi / card / netbanking', max_length=30)),
                ('failure_reason', models.TextField(blank=True)),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'status'], name='payments_pa_booking_57d6de_idx'),
        ),
    ]
