# Generated by Django 5.2 on 2026-08-28 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('vendors', '0009_vendorbankaccount_vendorbankaccountchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('mode', models.CharField(blank=True, help_text='IMPS / NEFT / RTGS / UPI', max_length=10)),
                ('razorpay_payout_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('fund_account_id', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Not sent yet'), ('queued', 'Queued (low balance)'), ('processing', 'Processing'), ('processed', 'Paid'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('utr', models.CharField(blank=True, help_text='Bank reference the vendor can quote to their branch', max_length=64)),
                ('failure_reason', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='payments.payment')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='payments_pa_status_b1a303_idx')],
            },
        ),
    ]
