# Generated by Django 5.2 on 2026-09-02 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(blank=True, help_text='Exactly as the bank holds it -- the business name, usually', max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=18)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('account_type', models.CharField(choices=[('CURRENT', 'Current'), ('SAVINGS', 'Savings')], default='CURRENT', max_length=10)),
                ('upi_id', models.CharField(blank=True, help_text='Optional. Handy for a fee settled by hand rather than through checkout.', max_length=64)),
                ('notes', models.TextField(blank=True, help_text='Anything the next person reconciling should know')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_bank_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'platform bank account',
                'verbose_name_plural': 'platform bank account',
            },
        ),
        migrations.CreateModel(
            name='PlatformBankAccountChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_account_masked', models.CharField(blank=True, max_length=32)),
                ('new_account_masked', models.CharField(blank=True, max_length=32)),
                ('old_ifsc', models.CharField(blank=True, max_length=11)),
                ('new_ifsc', models.CharField(blank=True, max_length=11)),
                ('old_upi', models.CharField(blank=True, max_length=64)),
                ('new_upi', models.CharField(blank=True, max_length=64)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_bank_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
