# Generated by Django 5.2 on 2026-09-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_platformbankaccount_platformbankaccountchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformbankaccountchange',
            name='changed_by',
        ),
        migrations.DeleteModel(
            name='PlatformBankAccount',
        ),
        migrations.DeleteModel(
            name='PlatformBankAccountChange',
        ),
    ]
