# Generated by Django 5.2 on 2026-07-24 05:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0009_booking_coupon_code_booking_discount_amount_and_more'),
        ('customers', '0002_customer_district_customer_pincode_customer_state'),
        ('services', '0006_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. WELCOME50', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FLAT', 'Flat Amount (₹)')], default='PERCENTAGE', max_length=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Max discount amount for percentage coupons', max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart total to use this coupon', max_digits=10)),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, help_text='Max number of times this coupon can be used across all customers (blank = unlimited)', null=True)),
                ('per_customer_limit', models.PositiveIntegerField(default=1, help_text='Max times a single customer can use this coupon')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='bookings.booking')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='customers.customer')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Monsoon Sale, First Booking Offer', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage (%)'), ('FLAT', 'Flat Amount (₹)')], default='PERCENTAGE', max_length=15)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 20 for 20%) or flat amount (e.g. 100 for ₹100)', max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Max discount amount (for percentage discounts only)', max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart total required to apply this discount', max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='services.servicecategory')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='services.service')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='services.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
