# Generated by Django 5.2 on 2026-08-26 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_serviceview'),
        ('services', '0006_alter_servicecategory_options_and_more'),
        ('vendors', '0008_vendor_services_vendor_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short headline, e.g. 3BHK ground-floor construction', max_length=200)),
                ('project_type', models.CharField(choices=[('HOUSE', 'Independent House'), ('APARTMENT', 'Apartment / Flat'), ('VILLA', 'Villa'), ('COMMERCIAL', 'Commercial Space'), ('RENOVATION', 'Renovation / Remodel'), ('INTERIOR', 'Interior Work'), ('OTHER', 'Other')], default='HOUSE', max_length=20)),
                ('description', models.TextField(help_text='What the project involves')),
                ('requirements', models.TextField(blank=True, help_text='Specific requirements, materials, finishes')),
                ('area_sqft', models.PositiveIntegerField(blank=True, help_text='Built-up area, if the customer knows it', null=True)),
                ('expected_budget', models.DecimalField(decimal_places=2, help_text='What the customer expects to spend. Vendors quote against this.', max_digits=12)),
                ('preferred_start_date', models.DateField(blank=True, help_text='When the customer wants work to begin', null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='How long the customer expects it to take', null=True)),
                ('bid_deadline', models.DateField(blank=True, help_text='Last day vendors may bid. Empty = open until awarded.', null=True)),
                ('address_text', models.CharField(blank=True, max_length=500)),
                ('address_state', models.CharField(blank=True, max_length=100)),
                ('address_district', models.CharField(blank=True, max_length=100)),
                ('address_pincode', models.CharField(blank=True, max_length=10)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('REJECTED', 'Rejected'), ('OPEN', 'Open for Bids'), ('AWARDED', 'Awarded'), ('IN_PROGRESS', 'Work In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Why an admin rejected it -- shown to the customer')),
                ('cancellation_reason', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(help_text='Decides which vendors this tender is shown to', on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='services.servicecategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='customers.customer')),
                ('subcategory', models.ForeignKey(blank=True, help_text='Narrows the vendors further. Empty = the whole category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='services.subcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tender_attachments/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tenders.tender')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text="The vendor's proposed budget", max_digits=12)),
                ('work_plan', models.TextField(blank=True, help_text='How the vendor intends to run the project')),
                ('timeline_days', models.PositiveIntegerField(blank=True, help_text='Days the vendor needs to finish', null=True)),
                ('proposed_start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Anything else for the customer')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Not Selected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='SUBMITTED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, help_text='When it was accepted or turned down', null=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenders.tender')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_bids', to='vendors.vendor')),
            ],
            options={
                'ordering': ['amount', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='tender',
            name='awarded_bid',
            field=models.OneToOneField(blank=True, help_text='The bid the customer accepted. The agreed price, work plan and milestones all hang off it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_for', to='tenders.tenderbid'),
        ),
        migrations.CreateModel(
            name='TenderMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Foundation complete', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower number = earlier')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REACHED', 'Reached'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('reached_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='tenders.tenderbid')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TenderProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('percent_complete', models.PositiveSmallIntegerField(blank=True, help_text='0-100, if the vendor gave a figure', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='tenders.tender')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_progress_updates', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tender_progress_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tenders.tenderprogressupdate')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tenderbid',
            constraint=models.UniqueConstraint(fields=('tender', 'vendor'), name='one_bid_per_vendor_per_tender'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['status', '-created_at'], name='tenders_ten_status_9589ca_idx'),
        ),
    ]
