# Generated by Django 5.2 on 2026-09-01 06:01

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderattachment',
            name='file',
            field=models.FileField(storage=config.storages.raw_storage, upload_to='tender_attachments/'),
        ),
    ]
