# Generated by Django 5.2 on 2026-09-02 10:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_alter_tenderattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percent of the accepted bid the customer pays the platform to confirm it. 0 confirms every bid for free.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('is_confirmation_fee_active', models.BooleanField(default=True, help_text='Off = choosing a bid awards the tender straight away, with nothing to pay. Existing unpaid fees are left alone.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tender Settings',
                'verbose_name_plural': 'Tender Settings',
            },
        ),
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('REJECTED', 'Rejected'), ('OPEN', 'Open for Bids'), ('PENDING_CONFIRMATION', 'Awaiting Confirmation'), ('AWARDED', 'Awarded'), ('IN_PROGRESS', 'Work In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenderbid',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SELECTED', 'Selected — awaiting confirmation'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Not Selected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='SUBMITTED', max_length=10),
        ),
        migrations.CreateModel(
            name='TenderConfirmationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, help_text="The rate at the moment the customer chose, not today's", max_digits=5)),
                ('bid_amount', models.DecimalField(decimal_places=2, help_text='What the bid was worth then', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Rupees due to the platform', max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('WAIVED', 'Waived')], db_index=True, default='PENDING', max_length=10)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('razorpay_signature', models.CharField(blank=True, max_length=128)),
                ('method', models.CharField(blank=True, help_text='upi / card / netbanking', max_length=30)),
                ('failure_reason', models.TextField(blank=True)),
                ('is_live', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Why it was waived or cancelled, for the record')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When it was cancelled or waived', null=True)),
                ('bid', models.ForeignKey(help_text='The bid this fee confirms', on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_fees', to='tenders.tenderbid')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_fees', to='tenders.tender')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='tenders_ten_status_180aeb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('tender',), name='one_pending_confirmation_fee_per_tender'), models.UniqueConstraint(condition=models.Q(('razorpay_order_id', ''), _negated=True), fields=('razorpay_order_id',), name='unique_confirmation_fee_order')],
            },
        ),
    ]
