# Generated by Django 5.2 on 2026-08-11 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0011_alter_booking_assigned_by'),
        ('customers', '0002_customer_district_customer_pincode_customer_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Turn the whole programme on or off in the app')),
                ('referrer_reward', models.DecimalField(decimal_places=2, default=50, help_text='What the existing customer earns per successful referral', max_digits=10)),
                ('friend_reward', models.DecimalField(decimal_places=2, default=50, help_text='What the invited friend gets on their first booking', max_digits=10)),
                ('home_banner_title', models.CharField(default='Refer and get free services', max_length=120)),
                ('home_banner_subtitle', models.CharField(default='Invite and get ₹{amount}*', max_length=120)),
                ('profile_card_title', models.CharField(default='Refer & earn ₹{amount}', max_length=120)),
                ('profile_card_subtitle', models.CharField(default='Get ₹{amount} when your friend completes their first booking', max_length=200)),
                ('profile_card_button', models.CharField(default='Refer now', max_length=40)),
                ('screen_title', models.CharField(default='Refer and get FREE services', max_length=120)),
                ('screen_description', models.TextField(default='Invite your friends to try our services. They get instant ₹{friend_amount} off. You win ₹{amount} once they take a service.')),
                ('step_one', models.CharField(default='Invite your friends & get rewarded', max_length=200)),
                ('step_two', models.CharField(default='They get ₹{friend_amount} on their first service', max_length=200)),
                ('step_three', models.CharField(default='You get ₹{amount} once their service is completed', max_length=200)),
                ('share_message', models.TextField(default='Hey! Book trusted home services with my code {code} and get ₹{friend_amount} off your first booking.', help_text='Sent when the customer shares. {code} is their referral code.')),
                ('terms', models.TextField(blank=True, default="Rewards are credited once your friend's first booking is completed. Rewards cannot be exchanged for cash.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Program',
                'verbose_name_plural': 'Referral Program',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_used', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending first booking'), ('EARNED', 'Earned — reward owed'), ('SETTLED', 'Settled')], default='PENDING', max_length=10)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('settled_note', models.CharField(blank=True, help_text='How the reward was paid out', max_length=200)),
                ('first_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_triggered', to='bookings.booking')),
                ('referred_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='customers.customer')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to='customers.customer')),
            ],
        ),
    ]
