# Generated by Django 5.2 on 2026-08-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('CUSTOMER', 'Customer App'), ('VENDOR', 'Vendor App')], max_length=10, unique=True)),
                ('logo', models.ImageField(upload_to='branding/')),
                ('app_name', models.CharField(blank=True, help_text='Shown under the logo on the splash and login screens', max_length=60)),
                ('tagline', models.CharField(blank=True, help_text='Small line under the app name', max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Branding',
                'verbose_name_plural': 'App Branding',
                'ordering': ['app'],
            },
        ),
    ]
