# Generated by Django 5.2 on 2026-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='services_json',
            field=models.JSONField(blank=True, default=list, help_text='List of selected services: [{id, name, price, qty}]'),
        ),
    ]
