# Generated by Django 5.2 on 2026-07-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_services_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='services_json',
        ),
    ]
