# Generated by Django 5.2 on 2026-07-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_services_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = shown first'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = shown first'),
        ),
    ]
