# Generated by Django 5.2 on 2026-09-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pricing_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('STARTING_FROM', 'Starting From'), ('PER_HOUR', 'Per Hour'), ('PER_DAY', 'Per Day'), ('PER_SQ_FT', 'Per Sq. Ft.'), ('PER_SQ_M', 'Per Sq. Meter'), ('PER_VISIT', 'Per Visit'), ('PER_ITEM', 'Per Item'), ('PER_UNIT', 'Per Unit'), ('PER_KM', 'Per Kilometer'), ('PER_ROOM', 'Per Room'), ('PER_SEAT', 'Per Seat'), ('PER_KG', 'Per Kg'), ('CUSTOM_QUOTE', 'Custom / Quote')], default='FIXED', help_text='How the price becomes an amount. Fixed = one flat price.', max_length=20),
        ),
    ]
