# Generated by Django 5.2 on 2026-09-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_pricing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Estimated duration in minutes. Only asked for, and only shown, on Fixed and Starting From services -- see `shows_duration`.'),
        ),
    ]
