# Generated by Django 5.2 on 2026-09-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tender_project_type',
            field=models.CharField(blank=True, choices=[('HOUSE', 'Independent House'), ('APARTMENT', 'Apartment / Flat'), ('VILLA', 'Villa'), ('COMMERCIAL', 'Commercial Space'), ('RENOVATION', 'Renovation / Remodel'), ('INTERIOR', 'Interior Work'), ('OTHER', 'Other')], help_text='For Custom / Quote services: the project type the tender form opens with. Empty = let the customer pick.', max_length=20),
        ),
    ]
