# Generated by Django 5.2 on 2026-08-10 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_assigned_by'),
        ('customers', '0002_customer_district_customer_pincode_customer_state'),
        ('support', '0001_initial'),
        ('vendors', '0006_vendor_last_assigned_at_vendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='raised_by',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor')], db_index=True, default='CUSTOMER', max_length=10),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='vendors.vendor'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('BOOKING', 'Booking Issue'), ('PAYMENT', 'Payment Issue'), ('ACCOUNT', 'Account Issue'), ('OTHER', 'Other'), ('VENDOR', 'Vendor Issue'), ('JOB', 'Job / Assignment Issue'), ('PAYOUT', 'Payout Issue'), ('APP', 'App / Technical Issue')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='sender',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='supportticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('vendor__isnull', True)), models.Q(('customer__isnull', True), ('vendor__isnull', False)), _connector='OR'), name='support_ticket_has_exactly_one_requester'),
        ),
    ]
