# Generated by Django 5.2 on 2026-07-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='home_display_limit',
            field=models.PositiveIntegerField(default=3, help_text="How many services to show on the home page. Rest appear in 'See all' page."),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subtitle',
            field=models.CharField(blank=True, help_text='e.g. Grooming essentials', max_length=200),
        ),
    ]
