# Generated by Django 5.2 on 2026-08-26 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_sections', '0002_homesection_home_display_limit_homesection_subtitle'),
        ('vendors', '0007_vendor_experience_years_vendor_is_pro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProVendorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Top rated electricians', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Hand-picked, verified pros', max_length=200)),
                ('home_display_limit', models.PositiveIntegerField(default=5, help_text="How many vendors to show on the home page. Rest appear in 'See all' page.")),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower = shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pro Vendor Sections',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProVendorSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home_sections.provendorsection')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_section_items', to='vendors.vendor')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('section', 'vendor')},
            },
        ),
    ]
