# Generated by Django 5.2 on 2026-07-20 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_booking_services_json'),
        ('customers', '0002_customer_district_customer_pincode_customer_state'),
        ('services', '0005_remove_service_services_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Work Type, Scope', max_length=200)),
                ('description', models.CharField(blank=True, help_text='e.g. Required — please select an option', max_length=500)),
                ('field_type', models.CharField(choices=[('single_select', 'Single Select (radio)'), ('multi_select', 'Multi Select (checkboxes)'), ('text', 'Text Input'), ('number', 'Number Input'), ('date', 'Date Picker'), ('photo', 'Photo Upload')], default='single_select', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('allow_custom', models.BooleanField(default=False, help_text='Allow customer to type a custom option (for select types)')),
                ('step_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='FormOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='service_forms.formstep')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='services.servicecategory')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='services.service')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='services.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Service Forms',
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(default=list, help_text='[{"step_id": 1, "title": "Work Type", "answer": "New Installation"}, ...]')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='bookings.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='customers.customer')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='service_forms.serviceform')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='formstep',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='service_forms.serviceform'),
        ),
    ]
