# Generated by Django 5.2 on 2026-07-23 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_customer_phone'),
        ('customers', '0002_customer_district_customer_pincode_customer_state'),
        ('reviews', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_admin_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, help_text='Display name for admin-created reviews. Leave blank for real customer reviews.', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='vendors.vendor'),
        ),
    ]
