# Generated by Django 5.2 on 2026-07-31 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeReviewProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Review',
                'verbose_name_plural': 'Admin Reviews (Fake)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reviews.review',),
        ),
        migrations.CreateModel(
            name='RealReviewProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Customer Review',
                'verbose_name_plural': 'Customer Reviews',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reviews.review',),
        ),
    ]
