# Generated by Django 5.2 on 2026-08-26 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_backfill_review_service'),
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tender',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='tenders.tender'),
        ),
    ]
