# Generated by Django 5.2 on 2026-08-11 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_district_customer_pincode_customer_state'),
        ('services', '0006_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_views', to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='services.service')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['customer', '-viewed_at'], name='customers_s_custome_d321f8_idx')],
                'unique_together': {('customer', 'service')},
            },
        ),
    ]
