# Generated by Django 5.2 on 2026-09-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_serviceview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
