# Generated by Django 5.2 on 2026-08-29 12:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0010_vendorbankaccount_name_match_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Free, Silver, Gold', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='One-line pitch shown under the plan name')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Amount per billing period. 0 = free plan.', max_digits=10)),
                ('billing_period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (3 months)'), ('HALF_YEARLY', 'Half-yearly (6 months)'), ('YEARLY', 'Yearly'), ('LIFETIME', 'Lifetime (never expires)')], default='MONTHLY', max_length=15)),
                ('features', models.TextField(blank=True, help_text='One benefit per line. Shown as bullets on the plan card.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans cannot be assigned to new vendors')),
                ('is_default', models.BooleanField(default=False, help_text='The plan a vendor lands on by default. Only one plan holds this.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'price', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=10)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, help_text='Blank = never expires', null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='What the vendor actually paid, if anything. Recorded by hand.', max_digits=10)),
                ('payment_reference', models.CharField(blank=True, help_text='UPI ref / receipt number, if you took payment offline', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who granted this subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='subscriptio_vendor__17e809_idx')],
            },
        ),
    ]
