# Generated by Django 5.2 on 2026-08-31 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('vendors', '0010_vendorbankaccount_name_match_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', max_length=10)),
                ('note', models.TextField(blank=True, help_text='What the vendor said when asking')),
                ('quoted_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_subscription', models.ForeignKey(blank=True, help_text='The term approving this request started', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_request', to='subscriptions.vendorsubscription')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upgrade_requests', to='subscriptions.subscriptionplan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subscription_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='subscriptio_status_62d8a0_idx')],
            },
        ),
    ]
