# Generated by Django 5.2 on 2026-07-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='last_assigned_at',
            field=models.DateTimeField(blank=True, help_text='When this vendor was last given a job (for round-robin)', null=True),
        ),
    ]
