# Generated by Django 5.2 on 2026-07-31 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_last_assigned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='last_assigned_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='status',
        ),
    ]
