# Generated by Django 5.2 on 2026-07-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_remove_vendor_last_assigned_at_remove_vendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='last_assigned_at',
            field=models.DateTimeField(blank=True, help_text='When this vendor was last given a job (for round-robin)', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline')], default='AVAILABLE', help_text='Available = free, Busy = on a job, Offline = not working', max_length=10),
        ),
    ]
