# Generated by Django 5.2 on 2026-08-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_last_assigned_at_vendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience, shown on the profile'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_pro',
            field=models.BooleanField(default=False, help_text='Show this vendor to customers as a Pro Vendor'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pro_banner',
            field=models.ImageField(blank=True, help_text='Wide image across the top of the profile page', null=True, upload_to='pro_vendor_banners/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pro_bio',
            field=models.TextField(blank=True, help_text="Longer intro shown on the vendor's profile page"),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pro_photo',
            field=models.ImageField(blank=True, help_text='Square headshot used on the cards and the profile page', null=True, upload_to='pro_vendor_photos/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pro_sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = shown first among pro vendors'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pro_tagline',
            field=models.CharField(blank=True, help_text='One-line pitch shown on the pro vendor card', max_length=160),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pro_title',
            field=models.CharField(blank=True, help_text='Headline under the name, e.g. Master Electrician', max_length=100),
        ),
    ]
