# Generated by Django 5.2 on 2026-08-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_servicecategory_options_and_more'),
        ('vendors', '0007_vendor_experience_years_vendor_is_pro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Limit to these individual services. Empty = the whole subcategory.', related_name='vendors', to='services.service'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='subcategories',
            field=models.ManyToManyField(blank=True, help_text='Limit to these subcategories. Empty = the whole category.', related_name='vendors', to='services.subcategory'),
        ),
    ]
