# Generated by Django 5.2 on 2026-08-28 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_vendor_services_vendor_subcategories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(help_text="Exactly as it appears on the bank's records", max_length=120)),
                ('account_number', models.CharField(max_length=18)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('branch_name', models.CharField(blank=True, max_length=120)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current')], default='SAVINGS', max_length=10)),
                ('upi_id', models.CharField(blank=True, max_length=64)),
                ('is_verified', models.BooleanField(default=False, help_text='An admin has confirmed these details belong to this vendor')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='vendors.vendor')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vendor bank account',
            },
        ),
        migrations.CreateModel(
            name='VendorBankAccountChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_account_masked', models.CharField(blank=True, max_length=32)),
                ('new_account_masked', models.CharField(blank=True, max_length=32)),
                ('old_ifsc', models.CharField(blank=True, max_length=11)),
                ('new_ifsc', models.CharField(blank=True, max_length=11)),
                ('old_upi', models.CharField(blank=True, max_length=64)),
                ('new_upi', models.CharField(blank=True, max_length=64)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bank_changes', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_changes', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
