# Generated by Django 5.2 on 2026-08-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_vendorbankaccount_vendorbankaccountchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbankaccount',
            name='name_match_score',
            field=models.FloatField(blank=True, help_text='0-1, how closely registered_name matches what was entered', null=True),
        ),
        migrations.AddField(
            model_name='vendorbankaccount',
            name='razorpayx_contact_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vendorbankaccount',
            name='razorpayx_fund_account_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vendorbankaccount',
            name='registered_name',
            field=models.CharField(blank=True, help_text='The name the bank holds against this account', max_length=160),
        ),
        migrations.AddField(
            model_name='vendorbankaccount',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorbankaccount',
            name='validation_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='vendorbankaccount',
            name='validation_status',
            field=models.CharField(choices=[('NOT_CHECKED', 'Not checked'), ('PENDING', 'Check in progress'), ('ACTIVE', 'Account is real'), ('INVALID', 'Account is not valid'), ('NAME_MISMATCH', 'Name does not match'), ('FAILED', 'Check could not be completed')], default='NOT_CHECKED', help_text='Result of the penny-drop check against the bank', max_length=15),
        ),
    ]
