# Generated by Django 5.2 on 2026-09-01 05:55

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_vendorbankaccount_name_match_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordocument',
            name='file',
            field=models.FileField(storage=config.storages.raw_storage, upload_to='vendor_documents/'),
        ),
    ]
