# Generated by Django 5.2 on 2026-09-01 09:13

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_alter_vendordocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordocument',
            name='file',
            field=models.FileField(storage=config.storages.private_storage, upload_to='vendor_documents/'),
        ),
    ]
