# Generated by Django 5.2 on 2026-09-03 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_alter_vendordocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='district',
            field=models.CharField(blank=True, help_text='District the vendor is based in', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, help_text='State the vendor is based in', max_length=100),
        ),
        migrations.CreateModel(
            name='VendorServiceRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('state_key', models.CharField(db_index=True, editable=False, help_text='Normalized form of `state`; set on save, never by hand.', max_length=100)),
                ('district', models.CharField(blank=True, help_text='Leave empty to cover the whole state.', max_length=100)),
                ('district_key', models.CharField(blank=True, db_index=True, editable=False, help_text='Normalized form of `district`; set on save, never by hand.', max_length=100)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_regions', to='vendors.vendor')),
            ],
            options={
                'ordering': ['state', 'district'],
                'unique_together': {('vendor', 'state_key', 'district_key')},
            },
        ),
    ]
