# Generated by Django 5.2 on 2026-07-20 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0005_remove_service_services_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Thoughtful curations', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. of our finest experiences', max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Curation Sections',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Text overlay on the card', max_length=200)),
                ('thumbnail', models.ImageField(upload_to='curation_thumbnails/')),
                ('video', models.FileField(upload_to='curation_videos/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, help_text='Service shown at the bottom of the video screen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curation_items', to='services.service')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='curations.curationsection')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
