# Generated by Django 5.2 on 2026-09-01 05:55

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curationitem',
            name='video',
            field=models.FileField(storage=config.storages.video_storage, upload_to='curation_videos/'),
        ),
    ]
