"""
Districts by state, for the pickers that stop people typing their own.

Generated data, not hand-written. Merged from two public datasets and
keyed onto the state names in regions.py, favouring recall: an extra or
renamed district in a dropdown costs a reader nothing, while a missing one
stops somebody completing their profile and so stops them booking at all.

It is therefore wider than the official list in places -- older district
names sit alongside the ones that replaced them -- and it will fall behind
as new districts are cut. **When somebody cannot find their district, add
it to the list below**; nothing else has to change, and the matching in
regions.py already treats spelling and case loosely.
"""

DISTRICTS_BY_STATE = {
    'Andaman and Nicobar Islands': [
        'Nicobars', 'North And Middle Andaman', 'South Andamans',
    ],
    'Andhra Pradesh': [
        'Alluri Sitharama Raju', 'Anakapalli', 'Anantapur', 'Ananthapuramu',
        'Annamayya', 'Bapatla', 'Chittoor', 'Dr. B.R. Ambedkar Konaseema',
        'East Godavari', 'Eluru', 'Guntur', 'Kakinada', 'Krishna', 'Kurnool',
        'Markapuram', 'Nandyal', 'Nellore', 'Ntr', 'Palnadu',
        'Parvathipuram Manyam', 'Polavaram', 'Prakasam',
        'Sri Potti Sriramulu Nellore', 'Sri Sathya Sai', 'Srikakulam',
        'Tirupati', 'Visakhapatnam', 'Vizianagaram', 'West Godavari',
        'YSR Kadapa',
    ],
    'Arunachal Pradesh': [
        'Anjaw', 'Bichom', 'Changlang', 'Dibang Valley', 'East Kameng',
        'East Siang', 'Kamle', 'Keyi Panyor', 'Kra Daadi', 'Kurung Kumey',
        'Leparada', 'Lohit', 'Longding', 'Lower Dibang Valley', 'Lower Siang',
        'Lower Subansiri', 'Namsai', 'Pakke Kessang', 'Papum Pare',
        'Shi Yomi', 'Siang', 'Tawang', 'Tirap', 'Upper Siang',
        'Upper Subansiri', 'West Kameng', 'West Siang',
    ],
    'Assam': [
        'Bajali', 'Baksa', 'Barpeta', 'Biswanath', 'Bongaigaon', 'Cachar',
        'Charaideo', 'Chirang', 'Darrang', 'Dhemaji', 'Dhubri', 'Dibrugarh',
        'Dima Hasao', 'Goalpara', 'Golaghat', 'Hailakandi', 'Hojai', 'Jorhat',
        'Kamrup', 'Kamrup Metro', 'Kamrup Metropolitan', 'Karbi Anglong',
        'Karimganj', 'Kokrajhar', 'Lakhimpur', 'Majuli', 'Marigaon',
        'Morigaon', 'Nagaon', 'Nalbari', 'Sivasagar', 'Sonitpur',
        'South Salmara-Mankachar', 'Tinsukia', 'Udalguri',
        'West Karbi Anglong',
    ],
    'Bihar': [
        'Araria', 'Arwal', 'Aurangabad', 'Banka', 'Begusarai', 'Bhagalpur',
        'Bhojpur', 'Buxar', 'Darbhanga', 'East Champaran (Motihari)', 'Gaya',
        'Gopalganj', 'Jamui', 'Jehanabad', 'Kaimur (Bhabua)', 'Katihar',
        'Khagaria', 'Kishanganj', 'Lakhisarai', 'Madhepura', 'Madhubani',
        'Munger', 'Munger (Monghyr)', 'Muzaffarpur', 'Nalanda', 'Nawada',
        'Pashchim Champaran', 'Patna', 'Purnia (Purnea)', 'Rohtas', 'Saharsa',
        'Samastipur', 'Saran', 'Sheikhpura', 'Sheohar', 'Sitamarhi', 'Siwan',
        'Supaul', 'Vaishali', 'West Champaran',
    ],
    'Chandigarh': [
        'Chandigarh',
    ],
    'Chhattisgarh': [
        'Balod', 'Baloda Bazar', 'Balodabazar-Bhatapara', 'Balrampur',
        'Balrampur-Ramanujganj', 'Bastar', 'Bemetara', 'Bijapur', 'Bilaspur',
        'Dakshin Bastar Dantewada', 'Dantewada (South Bastar)', 'Dhamtari',
        'Durg', 'Gariyaband', 'Gaurela-Pendra-Marwahi', 'Janjgir-Champa',
        'Jashpur', 'Kabeerdham', 'Kabirdham (Kawardha)',
        'Kanker (North Bastar)', 'Khairagarh-Chhuikhadan-Gandai', 'Kondagaon',
        'Korba', 'Korea', 'Korea (Koriya)', 'Mahasamund',
        'Manendragarh-Chirmiri-Bharatpur(M C B)',
        'Mohla-Manpur-Ambagarh Chouki', 'Mungeli', 'Narayanpur', 'Raigarh',
        'Raipur', 'Rajnandgaon', 'Sukma', 'Surajpur', 'Surguja',
    ],
    'Dadra and Nagar Haveli and Daman and Diu': [
        'Dadra And Nagar Haveli', 'Daman', 'Diu',
    ],
    'Delhi': [
        'Central', 'Central Delhi', 'East', 'East Delhi', 'New Delhi',
        'North', 'North Delhi', 'North East', 'North East Delhi',
        'North West', 'North West Delhi', 'Shahdara', 'South', 'South Delhi',
        'South East', 'South East Delhi', 'South West', 'South West Delhi',
        'West', 'West Delhi',
    ],
    'Goa': [
        'Kushavati', 'North Goa', 'South Goa',
    ],
    'Gujarat': [
        'Ahmedabad', 'Amreli', 'Anand', 'Aravalli', 'Arvalli', 'Banas Kantha',
        'Banaskantha (Palanpur)', 'Bharuch', 'Bhavnagar', 'Botad',
        'Chhota Udepur', 'Chhotaudepur', 'Dahod', 'Dangs', 'Dangs (Ahwa)',
        'Devbhoomi Dwarka', 'Devbhumi Dwarka', 'Gandhinagar', 'Gir Somnath',
        'Jamnagar', 'Junagadh', 'Kachchh', 'Kheda', 'Kheda (Nadiad)',
        'Mahesana', 'Mahisagar', 'Mehsana', 'Morbi', 'Narmada',
        'Narmada (Rajpipla)', 'Navsari', 'Panch Mahals',
        'Panchmahal (Godhra)', 'Patan', 'Porbandar', 'Rajkot',
        'Sabarkantha (Himmatnagar)', 'Surat', 'Surendranagar', 'Tapi (Vyara)',
        'Vadodara', 'Valsad',
    ],
    'Haryana': [
        'Ambala', 'Bhiwani', 'Charkhi Dadri', 'Faridabad', 'Fatehabad',
        'Gurgaon', 'Gurugram', 'Hansi', 'Hisar', 'Jhajjar', 'Jind', 'Kaithal',
        'Karnal', 'Kurukshetra', 'Mahendragarh', 'Mewat', 'Nuh', 'Palwal',
        'Panchkula', 'Panipat', 'Rewari', 'Rohtak', 'Sirsa', 'Sonipat',
        'Yamunanagar',
    ],
    'Himachal Pradesh': [
        'Bilaspur', 'Chamba', 'Hamirpur', 'Kangra', 'Kinnaur', 'Kullu',
        'Lahaul &amp; Spiti', 'Lahaul And Spiti', 'Mandi', 'Shimla',
        'Sirmaur', 'Sirmaur (Sirmour)', 'Solan', 'Una',
    ],
    'Jammu and Kashmir': [
        'Anantnag', 'Bandipora', 'Bandipore', 'Baramulla', 'Budgam', 'Doda',
        'Ganderbal', 'Jammu', 'Kargil', 'Kathua', 'Kishtwar', 'Kulgam',
        'Kupwara', 'Leh', 'Poonch', 'Pulwama', 'Rajouri', 'Ramban', 'Reasi',
        'Samba', 'Shopian', 'Srinagar', 'Udhampur',
    ],
    'Jharkhand': [
        'Bokaro', 'Chatra', 'Deoghar', 'Dhanbad', 'Dumka', 'East Singhbhum',
        'East Singhbum', 'Garhwa', 'Giridih', 'Godda', 'Gumla', 'Hazaribag',
        'Hazaribagh', 'Jamtara', 'Khunti', 'Koderma', 'Latehar', 'Lohardaga',
        'Pakur', 'Palamu', 'Ramgarh', 'Ranchi', 'Sahebganj', 'Sahibganj',
        'Saraikela Kharsawan', 'Seraikela-Kharsawan', 'Simdega',
        'West Singhbhum',
    ],
    'Karnataka': [
        'Bagalkot', 'Bagalkote', 'Ballari', 'Ballari (Bellary)', 'Belagavi',
        'Belagavi (Belgaum)', 'Bengaluru (Bangalore) Rural',
        'Bengaluru (Bangalore) Urban', 'Bengaluru Rural', 'Bengaluru South',
        'Bengaluru Urban', 'Bidar', 'Chamarajanagar', 'Chikballapur',
        'Chikkaballapura', 'Chikkamagaluru', 'Chikkamagaluru (Chikmagalur)',
        'Chitradurga', 'Dakshina Kannada', 'Davanagere', 'Davangere',
        'Dharwad', 'Gadag', 'Hassan', 'Haveri', 'Kalaburagi',
        'Kalaburagi (Gulbarga)', 'Kodagu', 'Kolar', 'Koppal', 'Mandya',
        'Mysuru', 'Mysuru (Mysore)', 'Raichur', 'Ramanagara', 'Shivamogga',
        'Shivamogga (Shimoga)', 'Tumakuru (Tumkur)', 'Udupi',
        'Uttara Kannada (Karwar)', 'Vijayapura (Bijapur)', 'Yadgir',
    ],
    'Kerala': [
        'Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kollam',
        'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad', 'Pathanamthitta',
        'Thiruvananthapuram', 'Thrissur', 'Wayanad',
    ],
    'Ladakh': [
        'Kargil', 'Leh Ladakh',
    ],
    'Lakshadweep': [
        'Agatti', 'Amini', 'Androth', 'Bithra', 'Chethlath', 'Kadmath',
        'Kalpeni', 'Kavaratti', 'Kilthan', 'Lakshadweep District', 'Minicoy',
    ],
    'Madhya Pradesh': [
        'Agar-Malwa', 'Alirajpur', 'Anuppur', 'Ashoknagar', 'Balaghat',
        'Barwani', 'Betul', 'Bhind', 'Bhopal', 'Burhanpur', 'Chhatarpur',
        'Chhindwara', 'Damoh', 'Datia', 'Dewas', 'Dhar', 'Dindori', 'Guna',
        'Gwalior', 'Harda', 'Hoshangabad', 'Indore', 'Jabalpur', 'Jhabua',
        'Katni', 'Khandwa', 'Khandwa (East Nimar)', 'Khargone', 'Mandla',
        'Mandsaur', 'Morena', 'Narsinghpur', 'Neemuch', 'Panna', 'Raisen',
        'Rajgarh', 'Ratlam', 'Rewa', 'Sagar', 'Satna', 'Sehore', 'Seoni',
        'Shahdol', 'Shajapur', 'Sheopur', 'Shivpuri', 'Sidhi', 'Singrauli',
        'Tikamgarh', 'Ujjain', 'Umaria', 'Vidisha',
    ],
    'Maharashtra': [
        'Ahilyanagar', 'Ahmednagar', 'Akola', 'Amravati', 'Aurangabad',
        'Beed', 'Bhandara', 'Buldhana', 'Chandrapur',
        'Chhatrapati Sambhajinagar', 'Dharashiv', 'Dhule', 'Gadchiroli',
        'Gondia', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur', 'Latur',
        'Mumbai', 'Mumbai City', 'Mumbai Suburban', 'Nagpur', 'Nanded',
        'Nandurbar', 'Nashik', 'Osmanabad', 'Palghar', 'Parbhani', 'Pune',
        'Raigad', 'Ratnagiri', 'Sangli', 'Satara', 'Sindhudurg', 'Solapur',
        'Thane', 'Wardha', 'Washim', 'Yavatmal',
    ],
    'Manipur': [
        'Bishnupur', 'Chandel', 'Churachandpur', 'Imphal East', 'Imphal West',
        'Jiribam', 'Kakching', 'Kamjong', 'Kangpokpi', 'Noney', 'Pherzawl',
        'Senapati', 'Tamenglong', 'Tengnoupal', 'Thoubal', 'Ukhrul',
    ],
    'Meghalaya': [
        'East Garo Hills', 'East Jaintia Hills', 'East Khasi Hills',
        'Eastern West Khasi Hills', 'North Garo Hills', 'Ri Bhoi',
        'South Garo Hills', 'South West Garo Hills', 'South West Khasi Hills',
        'West Garo Hills', 'West Jaintia Hills', 'West Khasi Hills',
    ],
    'Mizoram': [
        'Aizawl', 'Champhai', 'Hnahthial', 'Khawzawl', 'Kolasib', 'Lawngtlai',
        'Lunglei', 'Mamit', 'Saiha', 'Saitual', 'Serchhip', 'Siaha',
    ],
    'Nagaland': [
        'Chumoukedima', 'Dimapur', 'Kiphire', 'Kohima', 'Longleng', 'Meluri',
        'Mokokchung', 'Mon', 'Niuland', 'Noklak', 'Peren', 'Phek', 'Shamator',
        'Tseminyu', 'Tuensang', 'Wokha', 'Zunheboto',
    ],
    'Odisha': [
        'Angul', 'Balangir', 'Balasore', 'Bargarh', 'Bhadrak', 'Boudh',
        'Cuttack', 'Deogarh', 'Dhenkanal', 'Gajapati', 'Ganjam',
        'Jagatsinghapur', 'Jajpur', 'Jharsuguda', 'Kalahandi', 'Kandhamal',
        'Kendrapara', 'Kendujhar (Keonjhar)', 'Keonjhar', 'Khordha',
        'Koraput', 'Malkangiri', 'Mayurbhanj', 'Nabarangpur', 'Nayagarh',
        'Nuapada', 'Puri', 'Rayagada', 'Sambalpur', 'Sonepur', 'Sundargarh',
    ],
    'Puducherry': [
        'Karaikal', 'Mahe', 'Pondicherry', 'Puducherry', 'Yanam',
    ],
    'Punjab': [
        'Amritsar', 'Barnala', 'Bathinda', 'Faridkot', 'Fatehgarh Sahib',
        'Fazilka', 'Ferozepur', 'Gurdaspur', 'Hoshiarpur', 'Jalandhar',
        'Kapurthala', 'Ludhiana', 'Malerkotla', 'Mansa', 'Moga', 'Muktsar',
        'Nawanshahr (Shahid Bhagat Singh Nagar)', 'Pathankot', 'Patiala',
        'Rupnagar', 'S.A.S Nagar', 'Sahibzada Ajit Singh Nagar (Mohali)',
        'Sangrur', 'Shahid Bhagat Singh Nagar', 'Sri Muktsar Sahib',
        'Tarn Taran',
    ],
    'Rajasthan': [
        'Ajmer', 'Alwar', 'Balotra', 'Banswara', 'Baran', 'Barmer', 'Beawar',
        'Bharatpur', 'Bhilwara', 'Bikaner', 'Bundi', 'Chittorgarh', 'Churu',
        'Dausa', 'Deeg', 'Dholpur', 'Didwana-Kuchaman', 'Dungarpur',
        'Ganganagar', 'Hanumangarh', 'Jaipur', 'Jaisalmer', 'Jalore',
        'Jhalawar', 'Jhunjhunu', 'Jodhpur', 'Karauli', 'Kota', 'Nagaur',
        'Pali', 'Pratapgarh', 'Rajsamand', 'Sawai Madhopur', 'Sikar',
        'Sirohi', 'Sri Ganganagar', 'Tonk', 'Udaipur',
    ],
    'Sikkim': [
        'East Sikkim', 'Gangtok', 'Gyalshing', 'Mangan', 'Namchi',
        'North Sikkim', 'Pakyong', 'Soreng', 'South Sikkim', 'West Sikkim',
    ],
    'Tamil Nadu': [
        'Ariyalur', 'Chengalpattu', 'Chennai', 'Coimbatore', 'Cuddalore',
        'Dharmapuri', 'Dindigul', 'Erode', 'Kallakurichi', 'Kancheepuram',
        'Kanchipuram', 'Kanniyakumari', 'Kanyakumari', 'Karur', 'Krishnagiri',
        'Madurai', 'Mayiladuthurai', 'Nagapattinam', 'Namakkal', 'Nilgiris',
        'Perambalur', 'Pudukkottai', 'Ramanathapuram', 'Ranipet', 'Salem',
        'Sivaganga', 'Tenkasi', 'Thanjavur', 'Theni',
        'Thoothukudi (Tuticorin)', 'Tiruchirappalli', 'Tirunelveli',
        'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Tiruvarur', 'Vellore',
        'Viluppuram', 'Virudhunagar',
    ],
    'Telangana': [
        'Adilabad', 'Bhadradri Kothagudem', 'Hanumakonda', 'Hyderabad',
        'Jagitial', 'Jagtial', 'Jangaon', 'Jangoan',
        'Jayashankar Bhoopalpally', 'Jayashankar Bhupalapally',
        'Jogulamba Gadwal', 'Kamareddy', 'Karimnagar', 'Khammam',
        'Komaram Bheem Asifabad', 'Kumuram Bheem Asifabad', 'Mahabubabad',
        'Mahabubnagar', 'Mancherial', 'Medak', 'Medchal',
        'Medchal Malkajgiri', 'Mulugu', 'Nagarkurnool', 'Nalgonda',
        'Narayanpet', 'Nirmal', 'Nizamabad', 'Peddapalli', 'Rajanna Sircilla',
        'Rangareddy', 'Sangareddy', 'Siddipet', 'Suryapet', 'Vikarabad',
        'Wanaparthy', 'Warangal (Rural)', 'Warangal (Urban)',
        'Yadadri Bhuvanagiri',
    ],
    'Tripura': [
        'Dhalai', 'Gomati', 'Khowai', 'North Tripura', 'Sepahijala',
        'South Tripura', 'Unakoti', 'West Tripura',
    ],
    'Uttar Pradesh': [
        'Agra', 'Aligarh', 'Allahabad', 'Ambedkar Nagar', 'Amethi',
        'Amethi (Chatrapati Sahuji Mahraj Nagar)', 'Amroha',
        'Amroha (J.P. Nagar)', 'Auraiya', 'Ayodhya', 'Azamgarh', 'Baghpat',
        'Bahraich', 'Ballia', 'Balrampur', 'Banda', 'Bara Banki', 'Barabanki',
        'Bareilly', 'Basti', 'Bhadohi', 'Bijnor', 'Budaun', 'Bulandshahr',
        'Chandauli', 'Chitrakoot', 'Deoria', 'Etah', 'Etawah', 'Faizabad',
        'Farrukhabad', 'Fatehpur', 'Firozabad', 'Gautam Buddha Nagar',
        'Ghaziabad', 'Ghazipur', 'Gonda', 'Gorakhpur', 'Hamirpur',
        'Hapur (Panchsheel Nagar)', 'Hardoi', 'Hathras', 'Jalaun', 'Jaunpur',
        'Jhansi', 'Kannauj', 'Kanpur Dehat', 'Kanpur Nagar',
        'Kanshiram Nagar (Kasganj)', 'Kaushambi', 'Kushinagar (Padrauna)',
        'Lakhimpur - Kheri', 'Lalitpur', 'Lucknow', 'Maharajganj', 'Mahoba',
        'Mainpuri', 'Mathura', 'Mau', 'Meerut', 'Mirzapur', 'Moradabad',
        'Muzaffarnagar', 'Pilibhit', 'Pratapgarh', 'RaeBareli', 'Rampur',
        'Saharanpur', 'Sambhal (Bhim Nagar)', 'Sant Kabir Nagar',
        'Shahjahanpur', 'Shamali (Prabuddh Nagar)', 'Shravasti',
        'Siddharth Nagar', 'Sitapur', 'Sonbhadra', 'Sultanpur', 'Unnao',
        'Varanasi',
    ],
    'Uttarakhand': [
        'Almora', 'Bageshwar', 'Chamoli', 'Champawat', 'Dehradun', 'Haridwar',
        'Nainital', 'Pauri Garhwal', 'Pithoragarh', 'Rudraprayag',
        'Tehri Garhwal', 'Udham Singh Nagar', 'Uttarkashi',
    ],
    'West Bengal': [
        'Alipurduar', 'Bankura', 'Birbhum', 'Burdwan (Bardhaman)',
        'Cooch Behar', 'Dakshin Dinajpur',
        'Dakshin Dinajpur (South Dinajpur)', 'Darjeeling', 'Hooghly',
        'Howrah', 'Jalpaiguri', 'Jhargram', 'Kalimpong', 'Kolkata', 'Malda',
        'Murshidabad', 'Nadia', 'North 24 Parganas', 'Paschim Bardhaman',
        'Paschim Medinipur', 'Paschim Medinipur (West Medinipur)',
        'Purba Bardhaman', 'Purba Medinipur',
        'Purba Medinipur (East Medinipur)', 'Purulia', 'South 24 Parganas',
        'Uttar Dinajpur', 'Uttar Dinajpur (North Dinajpur)',
    ],
}
