# Generated by Django 5.2 on 2026-07-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_address_text_booking_location_lat_and_more'),
        ('services', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='services.subcategory'),
        ),
    ]
