# Generated by Django 5.2 on 2026-07-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='services_json',
            field=models.JSONField(blank=True, default=list, help_text='List of selected services: [{id, name, price, qty}]'),
        ),
    ]
