# Generated by Django 5.2 on 2026-07-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_services_json'),
        ('service_forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='services_json',
        ),
        migrations.AddField(
            model_name='booking',
            name='form_submission',
            field=models.ForeignKey(blank=True, help_text="Customer's filled form for this booking", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='service_forms.formsubmission'),
        ),
    ]
