# Generated by Django 5.2 on 2026-07-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_services_json_booking_form_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='services_json',
            field=models.JSONField(blank=True, default=list, help_text='List of selected services: [{id, name, price, qty}]'),
        ),
    ]
