# Generated by Django 5.2 on 2026-07-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_services_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='address_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='address_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
