# Generated by Django 5.2 on 2026-07-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_address_district_booking_address_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
