# Generated by Django 5.2 on 2026-07-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total discount applied', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_details',
            field=models.JSONField(blank=True, default=dict, help_text='Applied discount/coupon details'),
        ),
    ]
