# Generated by Django 5.2 on 2026-07-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_coupon_code_booking_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_by',
            field=models.CharField(blank=True, help_text="How the vendor was assigned: 'Manual' or 'Auto'", max_length=20),
        ),
    ]
