# Generated by Django 5.2 on 2026-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='assigned_by',
            field=models.CharField(blank=True, default='', help_text="How the vendor was assigned: 'Manual' or 'Auto'", max_length=20),
        ),
    ]
