# Generated by Django 5.2 on 2026-08-26 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_alter_booking_assigned_by'),
        ('vendors', '0007_vendor_experience_years_vendor_is_pro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='preferred_vendor',
            field=models.ForeignKey(blank=True, help_text='Pro vendor the customer asked for while booking. Only a request -- the admin still decides who is assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_bookings', to='vendors.vendor'),
        ),
    ]
