# Generated by Django 5.2 on 2026-07-31 08:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0011_alter_booking_assigned_by'),
        ('customers', '0002_customer_district_customer_pincode_customer_state'),
        ('dashboard', '0002_customernotification'),
        ('vendors', '0006_vendor_last_assigned_at_vendor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64, unique=True)),
                ('audience', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], max_length=10)),
                ('category', models.CharField(choices=[('BOOKING', 'Booking updates'), ('PAYMENT', 'Payments & refunds'), ('PROMO', 'Offers & promotions'), ('REVIEW', 'Reviews & ratings'), ('ACCOUNT', 'Account'), ('SYSTEM', 'System')], max_length=16)),
                ('title_template', models.CharField(max_length=200)),
                ('body_template', models.TextField(blank=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['audience', 'event'],
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('ALL_CUSTOMERS', 'All customers'), ('ALL_VENDORS', 'All vendors'), ('VERIFIED_VENDORS', 'Verified vendors only'), ('ALL_ADMINS', 'All admins')], max_length=20)),
                ('route', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=10)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='dashboard.adminuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], max_length=10)),
                ('push_enabled', models.BooleanField(default=True)),
                ('booking_updates', models.BooleanField(default=True)),
                ('payment_updates', models.BooleanField(default=True)),
                ('promotions', models.BooleanField(default=True)),
                ('review_updates', models.BooleanField(default=True)),
                ('account_updates', models.BooleanField(default=True)),
                ('system_updates', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='dashboard.adminuser')),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='customers.customer')),
                ('vendor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], max_length=10)),
                ('token', models.TextField(unique=True)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], default='ANDROID', max_length=10)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='dashboard.adminuser')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='customers.customer')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='vendors.vendor')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient_type', 'is_active'], name='notificatio_recipie_4b62c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMIN', 'Admin')], db_index=True, max_length=10)),
                ('event', models.CharField(db_index=True, max_length=64)),
                ('category', models.CharField(choices=[('BOOKING', 'Booking updates'), ('PAYMENT', 'Payments & refunds'), ('PROMO', 'Offers & promotions'), ('REVIEW', 'Reviews & ratings'), ('ACCOUNT', 'Account'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, help_text='Deep link the app opens on tap, e.g. /bookings/42', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('image_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('push_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('push_error', models.TextField(blank=True)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to='dashboard.adminuser')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_notifications', to='bookings.booking')),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.broadcast')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to='customers.customer')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_type', 'customer', 'is_read'], name='notificatio_recipie_9a6199_idx'), models.Index(fields=['recipient_type', 'vendor', 'is_read'], name='notificatio_recipie_80ab5d_idx'), models.Index(fields=['recipient_type', 'admin_user', 'is_read'], name='notificatio_recipie_bf4c0a_idx')],
            },
        ),
    ]
