# Generated by Django 5.2 on 2026-08-31 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_role_based_access'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='dashboard.adminprofile'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='dashboard.adminprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to='dashboard.adminprofile'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='admin_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to='dashboard.adminprofile'),
        ),
    ]
